@startuml State Transition Diagram

[*] --> 初期状態 : アプリ起動

state 初期状態 {
    初期状態 : タイトル名「アラーム」
    初期状態 : 追加ボタン： 表示
    初期状態 : 選択ボタン： 非表示
    初期状態 : ※初期アラームなどは設定されていない状態とする
}

初期状態 --> アラーム追加画面 : 「アラームを追加+」押下

state アラーム追加画面 {
    アラーム追加画面 : 時間設定 : 00~23
    アラーム追加画面 : 分設定 : 00~59
    アラーム追加画面 : サウンド設定 : 可能
    アラーム追加画面 : 保存ボタン : 表示
    アラーム追加画面 : キャンセルボタン : 表示
}

note left of アラーム追加画面
➖設定項目➖
◉ **秒**単位以下は不可
◉ **サウンド**音源はフリー素材(カスタム音源不可)。
音源をリスト表示し、クリックで音源確認可能
end note

アラーム追加画面 --> アラーム一覧画面 : 「保存」ボタン押下
アラーム一覧画面 --> アラーム追加画面 : 「アラームを追加+」押下

state アラーム一覧画面 {
アラーム一覧画面 : 設定アラーム１行(ON状態)
アラーム一覧画面 : ON・OFF切替ボタン : 表示
アラーム一覧画面 : 追加ボタン : 表示
アラーム一覧画面 : 選択ボタン : 表示
}

note left of アラーム一覧画面
➖記録項目➖
◉ アラーム初期状態: ON
◉ **5つ**までアラームを記憶できる ⇒ **ローカルストレージ**を利用
end note

アラーム一覧画面 --> アラーム削除画面 : 「選択」ボタン押下
アラーム削除画面 --> アラーム一覧画面 : 「削除」ボタン押下
アラーム削除画面 --> 初期状態
note on link
設定したアラームが0個になると
初期状態に遷移する
end note

state アラーム削除画面 {
    アラーム削除画面 : アラーム選択 : 可能
    アラーム削除画面 : 削除ボタン : 表示
    アラーム削除画面 : チェックボタン : 表示
}

note right of アラーム削除画面
設定されたアラームは各々また一括削除可能
end note

アラーム一覧画面 -[dotted]-> 内部状態 : 初期状態はONなので「**アラームON**」へ
内部状態 -[dotted]-> アラーム一覧画面
state 内部状態 {
    state アラームON: 設定アラーム１行(ON状態)
    state アラームOFF: 設定アラーム１行(OFF状態)

    アラームON --> アラームOFF : ON・OFF切替(OFF切替)
    アラームOFF --> アラームON : ON・OFF切替(ON切替)
}

アラームON --> アラーム鳴動 : 設定時刻になると音を鳴らす
アラーム鳴動 --> アラームOFF : 「停止ボタン」か「Enter」 押下で音を止める

state アラーム鳴動 {
    アラーム鳴動 : ダイアログボックス : 表示
    アラーム鳴動 : 停止ボタン : 表示
}

note right of アラーム鳴動
➖鳴動条件➖
◉ 端末の音量が0またはスリープ状態の場合、
音は**鳴らない**
◉ 機内モード時(Wi-FiやBluetoothのoff時)
または画面最小化時の場合でも、音は**鳴る**こと
◉ 同時鳴動不可(最新の一つ)
end note

@enduml